---
- name: show arrays
  hosts: ansmnode2.vpractice.local
  vars_files:
    - vars/users
  tasks:
    - name: print array values
      debug:
        msg: "user {{users.auser02.username }} has homedirectory {{users.auser02.homedir }} and shell {{users.auser02.shell }}"
...
